root: 
  controller: Root
  action: index
  
your: 
  controller: Product 
  action: helloWorld  

# sample: 
#   controller: Sample
#   action: index
#   params: 
#     param1: value1
  
  
# domain_route: 
#   'your.domain.com': 
#     container: YourDomain
#     action: index
#     params:
#       param1: value1