root: 
  controller: Root
  action: index
  params: 
    _ARGS: admin

admin:
  controller: Root
  action: index
  params:
    _ARGS: admin
  
resource:
  controller: Resource 
  action: include

install: 
  controller: Install
  action: install
  params: 
    _ARGS: admin
      
login: 
  controller: Security
  action: login
  params: 
    _ARGS: admin
    
logout: 
  controller: Security
  action: logout
  params: 
    _ARGS: admin
  
security: 
  controller: Security
  action: index
  params: 
    _ARGS: admin
    
domain_route: ~